library(dplyr)
library(tidyr)
data<-read.table("household_power_consumption.txt",sep=";",header=TRUE,dec=".",colClasses=c("character","character","character","character","character","character","character","character","character"))
data2<-filter(data,Date=="1/2/2007" | Date=="2/2/2007")
data2$Date<-as.character(data2$Date)
data2$Time<-as.character(data2$Time)
data2$Date=strptime(data2$Date,format="%d/%m/%Y")
data2$Global_active_power<-as.numeric(data2$Global_active_power)
data2$Global_reactive_power<-as.numeric(data2$Global_reactive_power)
data2$Voltage<-as.numeric(data2$Voltage)
data2$Global_intensity<-as.numeric(data2$Global_intensity)
data2$Sub_metering_1<-as.numeric(data2$Sub_metering_1)
data2$Sub_metering_2<-as.numeric(data2$Sub_metering_2)
data2$Sub_metering_3<-as.numeric(data2$Sub_metering_3)
data2$Time<-paste(data2$Date,data2$Time, sep=" ")
data2$Time<-strptime(data2$Time,format="%Y-%m-%d %H:%M:%S")

#Plot 2:
with(data2, plot(Time,Global_active_power,type="n",ylab="Global Active Power (kilowatts)",xlab=""))
lines(data2$Time,data2$Global_active_power,type="l")
dev.copy(png,"plot2.png")
dev.off()