library(dplyr)
library(tidyr)
data<-read.table("household_power_consumption.txt",sep=";",header=TRUE,dec=".",colClasses=c("character","character","character","character","character","character","character","character","character"))
data2<-filter(data,Date=="1/2/2007" | Date=="2/2/2007")
data2$Date<-as.character(data2$Date)
data2$Time<-as.character(data2$Time)
data2$Date=strptime(data2$Date,format="%d/%m/%Y")
data2$Global_active_power<-as.numeric(data2$Global_active_power)
data2$Global_reactive_power<-as.numeric(data2$Global_reactive_power)
data2$Voltage<-as.numeric(data2$Voltage)
data2$Global_intensity<-as.numeric(data2$Global_intensity)
data2$Sub_metering_1<-as.numeric(data2$Sub_metering_1)
data2$Sub_metering_2<-as.numeric(data2$Sub_metering_2)
data2$Sub_metering_3<-as.numeric(data2$Sub_metering_3)
data2$Time<-paste(data2$Date,data2$Time, sep=" ")
data2$Time<-strptime(data2$Time,format="%Y-%m-%d %H:%M:%S")

#Plot3:
with(data2, plot(Time,Sub_metering_1,type="n",ylab="Energy Sub Metering",xlab=""))
legend("topright", lty=1, col = c("black","blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
lines(data2$Time,data2$Sub_metering_1,type="l")
lines(data2$Time,data2$Sub_metering_2,type="l",col="red")
lines(data2$Time,data2$Sub_metering_3,type="l",col="blue")
dev.copy(png,"plot3.png")
dev.off()